# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Main tag to publish'
      additionalTag1:
        description: 'Other tag to add 1' 
jobs:

  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm shrinkwrap
      - run: npm publish --tag ${{ github.event.inputs.tag }}
      - run: npm dist-tag add @criticalmanufacturing/dev-tasks:${{github.event.inputs.tag}}
        if: ${{github.event.inputs.additionalTag1 != github.event.inputs.additionalTag1.default}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
